info:
  app:
    name: demo
    description: demo project

spring:
  profiles:
    active: local
    main:
      banner-mode: off

  web:
    resources:
      cache:
        period: 31536000
        cachecontrol:
          max-age: 31536000
      chain:
        html-application-cache: true
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /webjars/swagger-ui/**.*

server:
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  max-http-header-size: 16384

springdoc:
  version: '1.0.0'
  swagger-ui:
    path: "/api-docs/swagger-ui"
    disable-swagger-default-url: true
    syntax-highlight:
      theme: "arta"
  api-docs:
    path: "/api-docs/v3/openapi"

auth:
  basic:
    api:
      user: api
      password: guest

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'

sample:
  name: amal
  id: 90
