# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    machine: # executor type
      image: ubuntu-2004:202101-01 # comes with only JDK 11 (not using docker image as jib is not working with it for now due to missing certs)

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run:
          name: Install OpenJDK 15
          command: |
            sudo apt-get update && sudo apt-get install openjdk-15-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-15-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-15-openjdk-amd64/bin/javac
            java -version

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: echo $REGISTRY_USERNAME

      - run: ./gradlew clean build --build-cache

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

  another-job:
    docker:
      - image: adoptopenjdk/openjdk15-openj9:alpine-slim
      # Specify service dependencies here if necessary
      # - image: circleci/postgres:9.4
    steps:
      - run: echo "Just running another-job as a example"

workflows:
  version: 2.1
    my-flow:
      jobs:
        - build
        - another-job
